Aggiornata configurazione e sorgenti

diff --git a/sources/init b/sources/init
--- a/sources/init
+++ b/sources/init
@@ -20,27 +20,13 @@ for i in /dev/sd??
 do
     mount $i /storage || continue
     sz=`df | grep "/storage$" | grep -o '[0-9]*' | head -n 2 | tail -n 1`
-    [ $sz -gt 20000000 ] && break
+    [ $sz -gt 1000000 ] && break # (sz in KB) => ~1GB
     umount /storage
 done
 mount | grep /storage || error "Failed to mount /storage"
 mkdir -p /storage/casper
 
-PERSIST=`grep -o persistent /proc/cmdline`
-if [ -n "$PERSIST" ]
-then
-    if [ -e /storage/home-rw -a ! -f /storage/home-rw ]
-    then
-        rm -rf /storage/home-rw
-    fi
-    if [ ! -e /storage/home-rw ]
-    then
-        dd if=/dev/zero bs=1M count=0 seek=10240 of=/storage/home-rw
-        mkfs.ext2 /storage/home-rw
-    fi
-fi
-
-BASEURL='http://10.0.0.1/casper/'
+BASEURL='http://10.8.0.1/casper'
 mkdir -p /storage/torrent
 rm -rf /storage/torrent/*.torrent
 IMAGE=`cat /proc/cmdline | grep -o 'imgname=[^\ ]*' | grep -o '[^=]*$'`
@@ -51,19 +37,20 @@ for i in filesystem.squashfs kernel.img initrd.img
 do
     wget ${BASEURL}/${IMAGE}/$i.torrent
 done
+clear
+
 gettorrent *.torrent || error "Failed to download torrent"
 sync
 
+for i in filesystem.squashfs kernel.img initrd.img
+do
+    cp $i ../casper/
+done
+sync
+
 IP=`ip addr show dev eth0 | grep -o 'inet\ [^\ /]*' | cut -d\  -f2`
-CLASS=`echo $IP | cut -d. -f2`
-X=`echo $IP | cut -d. -f3`
-Y=`echo $IP | cut -d. -f4`
-let X=$X+96
-X=$(printf \\x$(printf $(printf %x $X)))
-[ ${CLASS} -eq 1 ] && HOSTNAME=`printf ioi-$X%02d $Y`
-[ ${CLASS} -eq 2 ] && HOSTNAME=worker$Y
-IP="eth0,${IP},255.0.0.0,10.0.0.1"
-LOCALE=it
+SUFFIX=`echo $IP | cut -d. -f4`
+HOSTNAME=`printf rig-%03d $SUFFIX`
 TZ=Europe/Rome
 cd /storage/casper
-kexec kernel.img initrd.img "boot=casper quiet splash username=ioi hostname=${HOSTNAME} ip=${IP} locale=${LOCALE} timezone=${TZ} ${PERSIST}" || error "kexec failed!"
+kexec kernel.img initrd.img "boot=casper hostname=${HOSTNAME} timezone=${TZ}" || error "kexec failed!"
